name: Generate Cred Instance
on:
  # Trigger on merging to master.
  push:
    branches:
      - master
  # As well as every 24 hours (at 0:00 UTC).
  schedule:
    - cron: 0 */12 * * * # every 12 hours temporarily

jobs:
  GenerateCredInstance:
    runs-on: self-hosted
    timeout-minutes: 360
    env:
      NODE_OPTIONS: --max_old_space_size=8192
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false # Required to make github pages deployment work correctly

      - name: Cache Data # Cache SourceCred Data, invalidating if any of the config changes or the SC version is updated
        uses: pat-s/always-upload-cache@v2.1.5
        with:
          path: '**/cache'
          key: MG-SC-${{ runner.os }}-${{ hashFiles('**/config.json', '**/sourcecred.json', '**/yarn.lock') }}

      - name: Install Packages 🔧
        run: yarn --frozen-lockfile

      - name: Load Data and Compute Cred 🧮
        run: yarn sourcecred go
        env:
          SOURCECRED_GITHUB_TOKEN: ${{ secrets.SOURCECRED_GITHUB_TOKEN }}
          SOURCECRED_DISCORD_TOKEN: ${{ secrets.SOURCECRED_DISCORD_TOKEN }}

      - name: Generate Analysis Files (accounts.json)
        run: yarn sourcecred analysis

      - name: Generate Frontend 🏗
        run: |
          yarn sourcecred site
          rm -rf ./site/{output,data,config,sourcecred.json}
          cp -r ./{output,data,config,sourcecred.json} ./site/

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: site
